version: '2'
services:
  redis:
    image: redis:3.2.4-alpine
    ports:
      - "6379:6379"
  plum:
    build: pulmap/.
    ports:
      - "3001:3000"
    links:
      - gblsolr:solr
      - rabbitmq
    environment:
      RABBIT_SERVER: amqp://rabbitmq:5672
  gblsolr:
    image: geoconcerns/geoblacklight-solr
    expose:
      - "8983"
    ports:
      - "9983:8983"
  rabbitmq:
    image: rabbitmq:3.6.5-management
    ports:
      - "5672:5672"
      - "15672:15672"
